# Generated by Django 4.1.3 on 2023-08-19 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("countryname", models.CharField(max_length=200)),
                ("countrycode", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Masjidregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("district", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("aliasname", models.CharField(max_length=400)),
                ("address", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="States",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statename", models.CharField(max_length=200)),
                ("state_code", models.CharField(max_length=100)),
                (
                    "countrycode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masjidapp.countries",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("districtname", models.CharField(max_length=200)),
                ("district_code", models.CharField(max_length=100)),
                (
                    "state_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masjidapp.states",
                    ),
                ),
            ],
        ),
    ]
